feat: Tag Component & ActionTag Component
alkong-dalkong/alkong-dalkong_fe pull request #29
Opened 2024-08-16 05:09 UTC by G0MTENG

## 변경 사항

- Tag 컴포넌트 개발
- 서버 컴포넌트와 클라이언트 컴포넌트로 분리할 필요가 있다고 판단하여 일반 Tag 컴포넌트와 Action Tag 컴포넌트로 분리
- Storybook 적용
- 추가적으로 원래 색 관련해서 primary | add | delete 이렇게 의미가 있도록 네이밍 하려고 했는데 "+추가" 인데 delete를 써야 하면 의미가 퇴색된다고 생각해서 primary | mint | gray로 하였습니다.

## 리뷰 필요

- 코드 리뷰 부탁드립니다 🥹

### 첨부 링크(옵션)
#### Tag 컴포넌트
<img width="210" alt="스크린샷 2024-08-16 오후 2 03 54" src="https://github.com/user-attachments/assets/05fbd016-db08-4a00-bf1e-3d3b2eef8123">

#### Action Tag 컴포넌트
<img width="229" alt="스크린샷 2024-08-16 오후 2 04 05" src="https://github.com/user-attachments/assets/2e4c91d3-faf6-4113-89d7-62bc834c227d">

#### 색 네이밍 변경의 이유 (같은 +추가 이지만 색이 다름)
<img width="307" alt="스크린샷 2024-08-16 오후 2 08 52" src="https://github.com/user-attachments/assets/cd01b1ea-77e5-4032-b28f-0081b977876a">

close #26

2024-08-16 05:26 UTC, KimDongGyun23 commented on src/components/ActionTag/ActionTag.tsx
> +      className={`${ActionTagColors[color]} rounded-[99px] px-[11px] py-[5px] text-body font-medium`}
'text-body font-medium' 이 부분을 'body-M'으로 축약 가능합니다.

다른 폰트 설정에서도 위와 같이 사용해주세요~

2024-08-16 05:33 UTC, KimDongGyun23 commented on src/components/ActionTag/ActionTag.tsx
> +      className={`${ActionTagColors[color]} rounded-[99px] px-[11px] py-[5px] text-body font-medium`}
'text-body font-medium' 이 부분을 'body-M'으로 축약 가능합니다.

다른 폰트 설정에서도 위와 같이 사용해주세요~

2024-08-16 05:35 UTC, G0MTENG commented on src/components/ActionTag/ActionTag.tsx
> +      className={`${ActionTagColors[color]} rounded-[99px] px-[11px] py-[5px] text-body font-medium`}
오 감사합니다 고쳐서 올려놓겠습니다

2024-08-16 05:37 UTC, G0MTENG commented on src/components/ActionTag/ActionTag.tsx
> +      className={`${ActionTagColors[color]} rounded-[99px] px-[11px] py-[5px] text-body font-medium`}
고쳤습니당

2024-08-16 05:48 UTC, KimDongGyun23 commented
현재의 태그에서는 버튼 내부에 { children }을 받도록 되어있네요.
이러한 상태로는 +버튼이나 -버튼에 대응하기가 조금 불편하지 않을까란 생각이 듭니다. 

예를 들어 " + 기침 " 이라는 버튼을 만들기 위해서는
```
<ActionTag color='mint' onClick={()=>{}}>
  <div className="flex" >
    { ... +버튼 이미지 } 
    { "기침" }
  </div>
</ActionTag>
```
이렇게 들어갈 것 같은데요, 매번 레이아웃을 설정하는 것보단 각 버튼에 맞도록 레이아웃을 구현해두는 것은 어떤가요?

add 버튼과 minus버튼, 기본 태그 버튼으로 나눈다면 조금 더 사용할 때에 편리하지 않을까요?
태그 이름만 입력받으면 되니까요. 또한, 각각의 컴포넌트의 기능도 명확해진다고 생각합니다.

2024-08-20 06:46 UTC, kimsuyeon0916 commented
interface 컨벤션 정해보면 좋을 것 같아요! 개인적으로는 I prefix 를 붙이는 것보다는 props 로 쓰이는 정보의 타입이면 Props postfix만 붙이는게 좋을 것 같은데 태윤님의 의견이 궁금합니다!

2024-08-20 06:50 UTC, kimsuyeon0916 commented
태윤님 지금 폴더 명이 대문자인 것도 함께 들어가서, 그 폴더 2개는 삭제해서 올려주셔야 할 것 같습니다!

2024-08-20 06:55 UTC, kimsuyeon0916 commented
또한 함수는 화살표함수로 적는건 어떨지 컨벤션을 정해보는것도 필요할 것 같습니다!

2024-08-20 07:22 UTC, kimsuyeon0916 requested changes

2024-08-20 07:22 UTC, kimsuyeon0916 commented on src/components/actionTag/ActionTag.tsx
> +}
해당 타입을 ReactNode 타입을 하신 이유가 있을까용?

import { type PropsWithChildren } from 'react' 하고 PropsWithChildren 타입을 받는건 어떻게 생각하시나용?

2024-08-20 07:22 UTC, kimsuyeon0916 commented on src/components/tag/Tag.tsx
> +  children?: string
children 이 컴포넌트가 아니고 string 이 들어간다면 children 보다는 name 혹은 title 이라고 프로퍼티명을 짓는게 더 나을 것 같은데 태윤님의 의견이 궁금합니다!

2024-08-20 07:22 UTC, kimsuyeon0916 commented on src/components/tag/Tag.tsx
> +export default function Tag({ children = '' }: ITagProps) {
children에 기본 값을 주는 건 굳이 필요 없을 것 같습니다!

2024-08-20 07:22 UTC, kimsuyeon0916 commented on src/components/actionTag/ActionTag.tsx
> +      + {props.children}
+, - 기호 대신 svg 파일이 들어가야 할 듯 합니다!

2024-08-20 07:22 UTC, kimsuyeon0916 commented on src/components/actionTag/ActionTag.tsx
> +interface IPlusMinusTagProps {
ActionTagProps 가 더 변수명이 직관적일 것 같습니다!

2024-08-20 07:22 UTC, kimsuyeon0916 commented on src/components/actionTag/ActionTag.tsx
> +ActionTag.Minus = Minus
```suggestion
'use client'
import { type PropsWithChildren } from 'react'

interface ActionTagProps {
  onClick?: () => void
  title?: string
  color: 'primary' | 'default'
}

const ActionTagColors = {
  primary: 'bg-mint-6 text-white',
  default: 'bg-gray-2 text-gray-7',
}

export const ActionTag = ({ children, color, onClick }: PropsWithChildren<ActionTagProps>) => {
  return (
    <button
      className={`${ActionTagColors[color]} body-M rounded-[99px] px-[11px] py-[5px]`}
      onClick={onClick}
    >
      {children}
    </button>
  )
}

export const Plus = ({ title, ...props }: ActionTagProps) => {
  return (
    <ActionTag {...props} color="primary">
      {/* svg 파일 추가 */}
      {title}
    </ActionTag>
  )
}

export const Minus = ({ title, ...props }: ActionTagProps) => {
  return (
    <ActionTag {...props} color="default">
      {/* svg 파일 추가 */}
      {title}
    </ActionTag>
  )
}

```

이렇게 코드 바꾸는건 어떤지 태윤님의 의견이 궁금합니다!

2024-08-27 08:15 UTC, KimDongGyun23 approved these changes
고생하셨습니다!

2024-08-28 04:23 UTC, kimsuyeon0916 approved these changes

2024-08-28 04:24 UTC, merged