Feature/#25 action button component
alkong-dalkong/alkong-dalkong_fe pull request #43
Opened 2024-08-20 14:15 UTC by G0MTENG

## 변경 사항

- 액션 버튼 컴포넌트 개발
- 스토리북 적용

## 리뷰 필요

- 확인 부탁드립니다 !
- 추가적으로 클릭했을 때 에니메이션 효과 적용했는데 디자인에 없는 내용이기도 하니까 별로면 삭제하겠습니다!

close #25 

<img width="357" alt="스크린샷 2024-08-20 오후 11 13 15" src="https://github.com/user-attachments/assets/79382d2f-1437-4234-b60a-18dad7e8caeb">
<img width="361" alt="스크린샷 2024-08-20 오후 11 15 00" src="https://github.com/user-attachments/assets/738fba0f-83da-4c82-b568-1a0f0031b1a2">

2024-08-21 03:09 UTC, KimDongGyun23 commented on src/components/Button/Button.tsx
> +  return <Button {...props} width="w-[335px]" height="h-14" />
width를 고정 픽셀로 주는 이유가 있나요?
화면 크기에 따라 가변적으로 변하는 것이 좀 더 자연스럽지 않을까요?

2024-08-21 03:09 UTC, KimDongGyun23 commented on src/components/Button/Button.tsx
> +  color = 'primary',
`primary?: boolean` 을 내려받아서 스타일을 변경해보는 것은 어떤가요?

``` typescript
<Button primary>main 버튼</Button>
<Button>sub 버튼</Button>
``` 

상위 컴포넌트에서 이 버튼이 어떤 역할을 하고 어떤 색상일지 직관적으로 알 수 있어서 저는 이렇게 자주 사용합니다. 편하신 방법으로 사용하시면 될 것 같아요 :)

2024-08-21 03:09 UTC, KimDongGyun23 commented on src/components/Button/Button.tsx
> +      className={`${width} ${height} flex-center rounded-xl ${ButtonColors[color]} active:scale-95`}
애니메이션을 원하시면 지속시간도 꼭 설정해주세요.
현재 상태는 조금 부자연스럽네요. 

또한, 버튼의 크기를 생각한다면 scale 같은 경우도 95% 보다는 97 / 98 정도가 적당해보입니다.

2024-08-21 03:09 UTC, KimDongGyun23 commented on src/components/Button/Button.tsx
> +}
Props와 Size를 나눈 이유가 있을까요?

컴포넌트의 메인 Props인데 이를 나누어서 선언하신 이유가 있을까요?
차라리 다른 곳에서 쪼개어서 사용하는 것은 어떠신지 궁금합니다.

2024-08-21 03:09 UTC, KimDongGyun23 commented on src/components/Button/Button.tsx
> +}
disabled도 내려받아서 설정해야할 것 같아요.

2024-08-21 08:45 UTC, KimDongGyun23 commented on src/components/button/Button.tsx
> +    >
button의 타입을 넘겨주었으면 합니다.

폼 내부의 버튼의 경우 'submit'으로 설정되는 경우가 있기에, 
기본값으로 'button'을 지정하고 'submit'일 경우 props로 내려주는건 어떨까요?

2024-08-21 15:17 UTC, kimsuyeon0916 requested changes

2024-08-21 15:17 UTC, kimsuyeon0916 commented on src/components/button/Button.tsx
> +export type Props = {
ButtonProps 라고 명칭하는게 더 좋을 것 같습니다!

2024-08-21 15:17 UTC, kimsuyeon0916 commented on src/components/button/Button.tsx
> +  height = 'h-full',
피그마상에서는 height 은 short/long 둘 다 동일해서 굳이 props 로 받을 필요 없을 것 같습니다!

2024-08-21 15:17 UTC, kimsuyeon0916 commented on src/components/button/Button.tsx
> +  height = 'h-full',
오히려 폰트 사이즈가 달라서 해당 부분을 달리 줘야할 듯 합니다!

2024-08-23 06:11 UTC, G0MTENG reviewed
애니메이션 효과 제거했고, disable, submit Props로 내려받도록 수정했습니다 ! Props -> ButtonProps로 이름 수정도 했습니다.

2024-08-23 08:05 UTC, KimDongGyun23 commented on src/components/button/Button.stories.tsx
> +  title: 'Components/Button',
Components/Button에서 Button으로 바꾸면 좋을 것 같습니다.

2024-08-23 08:05 UTC, KimDongGyun23 commented on src/components/button/Button.tsx
> +export const Button: React.FC<PropsWithChildren<ButtonProps>> = ({
React.FC를 지양한다는 말이 많아서 해당 글들을 찾아보면 좋을 것 같습니다.

```typescript
export const Button = ({...}: PropsWithChildren<ButtonProps>) => {}
```

2024-08-23 08:05 UTC, KimDongGyun23 commented on src/components/button/Button.tsx
> +  submit = false,
submit 보다는 button의 type 속성을 나타내는 type으로 표현하면 좋을 것 같습니다. handleClick이 아닌 onClick으로 props를 내리는 것과 같은 논리입니다.

2024-08-23 08:05 UTC, KimDongGyun23 commented on src/components/button/Button.tsx
> +  fontSize = 'md',
디자인을 참고했을 때, height와 fontSize를 함께 설정하면 좋을 것 같습니다.

작은 버튼의 경우 height가 52px, fontSize가 headline-B 이며,
큰 버튼의 경우 height가 56px, fontSize가 subtitle-B 입니다.

이를 하나의 props로 내려주어 설정한다면 보다 편리할 것 같습니다.

2024-08-24 04:43 UTC, G0MTENG reviewed
변경 사항 올렸습니다 확인부탁드립니다 ~!

2024-08-24 05:01 UTC, KimDongGyun23 approved these changes
고생하셨습니다 :)

2024-08-25 05:53 UTC, kimsuyeon0916 approved these changes

2024-08-26 02:22 UTC, merged