feat: 모달 컴포넌트
alkong-dalkong/alkong-dalkong_fe pull request #73
Opened 2024-08-26 04:09 UTC by G0MTENG

## 변경 사항

- 모달 컴포넌트
- 스토리북 추가

## 리뷰 필요

- 모달 컴포넌트

### 첨부 링크(옵션)
<img width="1140" alt="스크린샷 2024-08-26 오후 1 09 45" src="https://github.com/user-attachments/assets/1067b14f-31ab-4665-a833-276f46139706">

close #44

2024-08-26 07:46 UTC, kimsuyeon0916 commented
레이아웃이나 타이포그래피의 경우에는 디자인 시스템에서 등록한 유틸리티 클래스가 있으니까 되도록이면 해당 구문을 이용해서 하는게 가독성도 좋고 더 간편할 듯 합니다~! 시간 되시면 리팩토링하면 좋을 것 같습니다!

2024-08-26 07:55 UTC, kimsuyeon0916 commented
> 레이아웃이나 타이포그래피의 경우에는 디자인 시스템에서 등록한 유틸리티 클래스가 있으니까 되도록이면 해당 구문을 이용해서 하는게 가독성도 좋고 더 간편할 듯 합니다~! 시간 되시면 리팩토링하면 좋을 것 같습니다!

2024-08-26 08:00 UTC, kimsuyeon0916 commented
1. 모달 열렸을 때 배경 스크롤 안되게 전에 useScrollLock 공통 훅 활용해서 적용해놓아주시면 감사할 것 같습니다! 
활용 커밋: 8488862da7da698be1a47b93f76903368c395461

2. 아래의 모달 버전은 별도로 존재하지 않나요?! 없어서 여쭤봅니다~!
    <img width="458" alt="image" src="https://github.com/user-attachments/assets/a4b3ecd0-5574-4ee8-bfb7-3c9f898c0ce6">

3. 작은 해상도의 모바일로 봤을 때 깨지는 문제가 있습니다~! 스토리북 참고하셔서 확인해보면 좋을 듯 하네요.
    <img width="599" alt="image" src="https://github.com/user-attachments/assets/57271046-633a-4b11-a947-7d0faafadf4d">

2024-08-26 08:02 UTC, kimsuyeon0916 commented
고생많으셨습니다! 커뮤니케이션 비용이 많이 드는 것을 방지하기 위해 PR 남겨주실 때 인지할 내용은 리뷰 필요에 좀 더 자세히 적어주셨으면 좋겠습니다..! 부탁드립니다~!

merge, test 등은 저희 컨벤션에 존재하지 않는 컨벤션인 것 같아 해당 부분도 확인 부탁드립니다!

2024-08-26 08:03 UTC, kimsuyeon0916 requested changes

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/app/page.tsx
use client 는 page 가 아닌 Modal 컴포넌트에 추가해야 할 것 같습니다.

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/hooks/useModal.ts
> +  // [ modal, openModal, closeModal ]
주석 처리가 되어있는 이유는 무엇인가요?

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/components/modal/Title.tsx
> +    <div className="text-subtitle font-bold leading-subtitle tracking-[-2%] text-black">
```suggestion
    <div className="subtitle-B text-black">
```

이미 존재하는 유틸리티 클래스를 활용하면 좋을 듯 합니다~

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/components/modal/Modal.tsx
> +}
타입에 들어가는 프로퍼티는 소문자가 좋을 것 같습니다~!

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/components/modal/Modal.tsx
> +}
React.FC 를 추가하신 이유가 뭘까요?! 되도록이면 React import 문을 이용해서 추가하면 해당 구문을 간단하게 할 수 있을 것 같습니다

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/hooks/useModal.ts
useBoolean 훅을 만들어서 사용해도 좋을 것 같네요~!

[관련 논의](https://github.com/alkong-dalkong/alkong-dalkong_fe/pull/54#discussion_r1727166164)를 이전 PR 에서 나누었으니 참고하면 좋을 것 같습니다!

2024-08-26 08:03 UTC, kimsuyeon0916 commented on src/components/modal/Modal.tsx
> +  const modalSize = size === 'md' ? 'h-[214px]' : 'h-[276px]'
modal에 사이즈 구분이 필요한 이유가 무엇인가요? 피그마상으로 파악하기 힘들어서 여쭤봅니다~

2024-08-26 14:27 UTC, G0MTENG commented on src/app/page.tsx
수정했습니다 !

2024-08-26 14:30 UTC, G0MTENG commented on src/hooks/useModal.ts
> +  // [ modal, openModal, closeModal ]
() => setState(true) 이렇게 return 하는게 직관적이지 않아서 설명을 돕기 위해 주석처리한 것입니다
오히려 가독성을 해친다면 삭제하겠습니다

2024-08-26 14:31 UTC, G0MTENG commented on src/components/modal/Title.tsx
> +    <div className="text-subtitle font-bold leading-subtitle tracking-[-2%] text-black">
감사합니다 초기에 짠 코드라 제가 실수를 했네용 ,,, ㅎㅎ 수정했습니다 ~

2024-08-26 14:35 UTC, G0MTENG commented on src/components/modal/Modal.tsx
> +}
<Modal.title title="우리 가족 그룹의 초대 코드?" /> 이렇게 사용하기보다
<Modal.Title title="우리 가족 그룹의 초대 코드?" /> 이렇게 사용하려구 짠 코드입니다 !

Reac.FC를 저도 지양하려고 했지만 ,,, Modal 컴포넌트의 프로퍼티로 넘겨주는 방법이 저 방법밖에 생각이 안 나서 저렇게 적용했습니다 ㅜㅜ

2024-08-26 14:37 UTC, G0MTENG commented on src/hooks/useModal.ts
useBoolean 훅이 자주 사용된다면 추후 적용하도록 하겠습니다 :D

2024-08-26 14:39 UTC, G0MTENG commented on src/components/modal/Modal.tsx
> +  const modalSize = size === 'md' ? 'h-[214px]' : 'h-[276px]'
두 모달의 height가 달라서 저렇게 적용했습니다 !

<img width="272" alt="스크린샷 2024-08-26 오후 11 38 03" src="https://github.com/user-attachments/assets/17c3404f-cbb1-45bf-8803-f8ed6eacf2c1">
<img width="267" alt="스크린샷 2024-08-26 오후 11 38 21" src="https://github.com/user-attachments/assets/94cb9cec-84fc-45b6-83cc-deb031485368">

2024-08-26 16:44 UTC, KimDongGyun23 commented on src/components/modal/Modal.tsx
> +  const modalSize = size === 'md' ? 'h-[214px]' : 'h-[276px]'
현재 작성 중인 리뷰는 지극히 개인적인 의견이고 개인마다 스타일이 있기 때문에 반영안하셔도 됩니다.

저의 경우에는 `width`나 `height`의 설정을 꺼려하는 편입니다.
여러 해상도에 대응해야 하므로 어디선가 어긋나는 부분이 있기 마련이지요.

그래서 위와 같은 모달의 사이즈의 경우는 다음과 같이 설정합니다.

- 높이 관련
  - 모달의 content 부분 ( 내용물 )을 `flex-column` 을 적용할 수 있습니다.
  - 이는 전체 높이를 설정하지 않아도, 내용물의 높이에 맞도록 컨테이너의 높이가 설정됩니다.

- 너비 관련
  - 모바일 뷰일 경우 너비는 되도록 `auto`와 `full`을 이용하는 편입니다.
  - width 를 직접 설정할 경우에는. 반응형으로 모든 해상도에 대하여 확인해 볼 필요가 있다고 생각합니다.

2024-08-27 03:56 UTC, KimDongGyun23 commented on src/components/modal/Modal.stories.tsx
> +        <div className="mt-[16px] flex w-3/5 justify-between">
`width`와 `justify-between`을 설정한 것으로 보아서는
너비를 3/5만큼 설정하고 양 옆으로 흩뿌리겠다는 의도로 생각이 듭니다.

이런 경우에는 `flex` 와 `gap` 속성을 이용한다면
너비 설정으로 인하여 넘쳐 흐르는 부분에 대한 고민을 줄일 수 있어요.
또한, 어떤 해상도에서든 요소들 사이의 간격을 일정하게 고정시킬 수도 있습니다.

현재의 부분에 대해서는 가변적인 최대 너비에 구애받지 않고 간격을 일정하게 설정할 수 있는 점에서 매력적일 수 있을 것 같네요.

2024-08-27 03:56 UTC, KimDongGyun23 commented on src/components/modal/Modal.tsx
> +          <button onClick={onClose} className="mb-[4px] ml-auto mr-[16px] mt-[20px] block w-[28px]">
type='button'은 꼭 설정해주세요.
저도 이 부분을 맨날 놓치곤 하는데 예상치 못한 상황이 초래될 수 있더라고요.

`margin` 속성이 되게 많이 사용되었는데 앞서 설명드린 `flex-column`을 이용했을 경우의 장점을 하나 더 말씀드릴게요!

이런 부분에서 `align-self`를 이용한다면 원하는 부분만 정렬시킬 수 있어요!
X표시 아이콘만 혼자 오르쪽 정렬을 시킬 수 있는거죠. 
그렇기에 조금 더 편리하게 코드를 구현할 수 있을거에요.

2024-08-27 03:56 UTC, KimDongGyun23 commented on src/components/modal/Modal.tsx
> +            <CloseIcon />
수연님이 구현해주신 로직에 따르면 아이콘들은 Icon 컴포넌트를 활용하는 것이 맞을 것 같아요.

2024-08-27 03:56 UTC, KimDongGyun23 commented on src/components/modal/Modal.stories.tsx
> +        <Modal.SubTitle title="사람에게 가족 코드를 공유해 보세요!" />
subtitle이 두 번 사용되어 의미를 잃는다는 점과
`Modal.XX` 보다 일반 요소들이 더 많이 사용된다는 점에서

어쩌면 Title과 SubTitle을 굳이 지정하지 않고 사용하는 곳에서 직접 입력해도 괜찮을 것 같네요.

이건 조금 다른 이야기지만, 제가 디자인을 하는 경우에는
h1, h2, ... p 등등 글자 태그들에 스타일을 지정하고 시작합니다.

예를 들면,
```javascript
h1: 20px, 두껍게
h2: 18px, 중간
h3: 16px, 얇게
....
```

이런 방식을 사용했을 때 Title이나 Subtitle 등 스타일 컴포넌트를 별도 생성할 필요없이 좋더라고요.
나중에 다른 프로젝트에서 사용하시면 좋을 것 같습니다. :)

2024-08-27 03:56 UTC, KimDongGyun23 commented on src/hooks/useModal.ts
> +  // [ modal, openModal, closeModal ]
가독성을 위해서라면 해당 부분을 함수로 만들어서 내보내면 될 것 같습니다.
이름을 통해서 충분히 유추 가능할 것 같아요.

2024-08-27 03:56 UTC, KimDongGyun23 commented on src/hooks/useModal.ts
현재 작성하신 내용을 저는 `useBoolean` 으로 사용합니다.

물론 이름은 개인적일 수 있으나, 해당 로직을 다른 곳에서 사용할 수도 있기에 범용적인 이름으로 바꾸면 좋을 것 같아요!

2024-08-28 05:12 UTC, G0MTENG commented on src/components/modal/Modal.stories.tsx
> +        <div className="mt-[16px] flex w-3/5 justify-between">
이 부분은 gap으로 수정했습니다 !

2024-08-28 05:14 UTC, G0MTENG commented on src/components/modal/Modal.tsx
> +          <button onClick={onClose} className="mb-[4px] ml-auto mr-[16px] mt-[20px] block w-[28px]">
button에 type='button' 추가했습니다 !

X 아이콘은 relative position을 사용하였습니다 ~

```js
<div className="flex-column relative w-[87.2%]  max-w-[390px] rounded-[12px] bg-white pb-[24px] pt-[52px]">
          <button onClick={onClose} type="button" className="absolute right-[16px] top-[20px]">
            <Icon name="close" />
          </button>
```

2024-08-28 05:15 UTC, G0MTENG commented on src/components/modal/Modal.tsx
> +            <CloseIcon />
넵 <Icon /> 컴포넌트를 사용해서 수정했습니다 !!

2024-08-28 05:16 UTC, G0MTENG commented on src/hooks/useModal.ts
useBoolean 훅으로 수정했습니다 !

2024-08-28 05:21 UTC, G0MTENG commented on src/hooks/useModal.ts
> +  // [ modal, openModal, closeModal ]
useBoolean 훅으로 교체했습니다

2024-08-28 05:22 UTC, G0MTENG commented on src/components/modal/Modal.tsx
> +}
컴포넌트의 프로퍼티 둘 다 삭제하여 `PropsWithChidren<ModalProps>` 다음과 같이 사용하도록 변경했습니다

2024-08-28 05:23 UTC, G0MTENG commented on src/components/modal/Modal.tsx
> +  const modalSize = size === 'md' ? 'h-[214px]' : 'h-[276px]'
size props로 받는 것 삭제하고 가변적으로 모달의 height가 커지도록 수정했습니다 감사합니다 :D

2024-08-29 04:53 UTC, KimDongGyun23 approved these changes
리뷰 사항들 모두 반영 확인했습니다. 고생하셨습니다. :)

2024-08-29 13:48 UTC, kimsuyeon0916 approved these changes
태윤님~! 수정사항 반영하시느라 고생많으셨습니다~!

2024-08-30 00:29 UTC, merged